name: Docker Build and Publish
on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            molero/jenkins-inbound-agent-docker:latest
      - name: Tag and Push Docker Image to Docker Hub and GitHub Package Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            molero/jenkins-inbound-agent-docker:latest
            docker.pkg.github.com/${{ github.repository }}/jenkins-inbound-agent-docker:latest
